export const wordList = [
    { dutch: 'absoluut', english: 'absolutely' },
    { dutch: 'accepteren', english: 'to accept' },
    { dutch: 'actie', english: 'action' },
    { dutch: 'actief', english: 'active' },
    { dutch: 'activiteit', english: 'activity' },
    { dutch: 'adres', english: 'address' },
    { dutch: 'advies', english: 'advice' },
    { dutch: 'agent', english: 'agent' },
    { dutch: 'al', english: 'already' },
    { dutch: 'alle', english: 'all' },
    { dutch: 'alleen', english: 'only' },
    { dutch: 'als', english: 'if/when' },
    { dutch: 'ander', english: 'other' },
    { dutch: 'antwoord', english: 'answer' },
    { dutch: 'arm', english: 'arm' },
    { dutch: 'artikel', english: 'article' },
    { dutch: 'aspect', english: 'aspect' },
    { dutch: 'auteur', english: 'author' },
    { dutch: 'automatisch', english: 'automatically' },
    { dutch: 'baby', english: 'baby' },
    { dutch: 'baas', english: 'boss' },
    { dutch: 'bank', english: 'bank' },
    { dutch: 'basis', english: 'base' },
    { dutch: 'bed', english: 'bed' },
    { dutch: 'beide', english: 'both' },
    { dutch: 'beïnvloeden', english: 'to influence' },
    { dutch: 'begin', english: 'get started' },
    { dutch: 'beginnen', english: 'to begin' },
    { dutch: 'bespreken', english: 'discuss' },
    { dutch: 'beter', english: 'better' },
    { dutch: 'bezig', english: 'busy' },
    { dutch: 'bier', english: 'beer' },
    { dutch: 'bijten', english: 'to bite' },
    { dutch: 'bitter', english: 'bitter' },
    { dutch: 'blauw', english: 'blue' },
    { dutch: 'bloed', english: 'blood' },
    { dutch: 'bodem', english: 'bottom' },
    { dutch: 'boek', english: 'book' },
    { dutch: 'boot', english: 'boat' },
    { dutch: 'breng', english: 'bring' },
    { dutch: 'broer', english: 'brother' },
    { dutch: 'brood', english: 'bread' },
    { dutch: 'bruin', english: 'brown' },
    { dutch: 'bus', english: 'bus' },
    { dutch: 'café', english: 'cafe' },
    { dutch: 'categorie', english: 'category' },
    { dutch: 'centrum', english: 'centre' },
    { dutch: 'collega', english: 'colleague' },
    { dutch: 'combinatie', english: 'combination' },
    { dutch: 'communicatie', english: 'communication' },
    { dutch: 'computer', english: 'computer' },
    { dutch: 'conclusie', english: 'conclusion' },
    { dutch: 'consequentie', english: 'consequence' },
    { dutch: 'contact', english: 'contact' },
    { dutch: 'crisis', english: 'crisis' },
    { dutch: 'cultureel', english: 'cultural' },
    { dutch: 'cultuur', english: 'culture' },
    { dutch: 'daar', english: 'there' },
    { dutch: 'dag', english: 'day' },
    { dutch: 'dan', english: 'then' },
    { dutch: 'danken', english: 'to thank' },
    { dutch: 'dansen', english: 'to dance' },
    { dutch: 'dat', english: 'that' },
    { dutch: 'de', english: 'the' },
    { dutch: 'deel', english: 'part' },
    { dutch: 'denken', english: 'to think' },
    { dutch: 'derde', english: 'third' },
    { dutch: 'deze', english: 'this' },
    { dutch: 'diep', english: 'deep' },
    { dutch: 'ding', english: 'thing' },
    { dutch: 'direct', english: 'directly' },
    { dutch: 'directeur', english: 'director' },
    { dutch: 'discussie', english: 'discussion' },
    { dutch: 'dit', english: 'this' },
    { dutch: 'dochter', english: 'daughter' },
    { dutch: 'doen', english: 'to do' },
    { dutch: 'dokter', english: 'doctor' },
    { dutch: 'dom', english: 'dumb' },
    { dutch: 'dood (zelfst. nw.)', english: 'death' },
    { dutch: 'dood (bijv. nw.)', english: 'dead' },
    { dutch: 'door', english: 'door' },
    { dutch: 'drie', english: 'three' },
    { dutch: 'drinken', english: 'drink' },
    { dutch: 'dromen', english: 'to dream' },
    { dutch: 'droom', english: 'dream' },
    { dutch: 'dubbel', english: 'double' },
    { dutch: 'dun', english: 'thin' },
    { dutch: 'economie', english: 'economy' },
    { dutch: 'een', english: 'a' },
    { dutch: 'eerst', english: 'first' },
    { dutch: 'effect', english: 'effect' },
    { dutch: 'eind', english: 'end' },
    { dutch: 'eindeloos', english: 'endless' },
    { dutch: 'eindigen', english: 'to end' },
    { dutch: 'eiland', english: 'island' },
    { dutch: 'ei', english: 'egg' },
    { dutch: 'elk', english: 'each' },
    { dutch: 'emotie', english: 'emotion' },
    { dutch: 'emotioneel', english: 'emotional' },
    { dutch: 'en', english: 'and' },
    { dutch: 'energie', english: 'energy' },
    { dutch: 'Engels', english: 'english' },
    { dutch: 'enorm', english: 'enormous' },
    { dutch: 'er', english: 'there' },
    { dutch: 'experiment', english: 'experiment' },
    { dutch: 'fabriek', english: 'factory' },
    { dutch: 'factor', english: 'factor' },
    { dutch: 'familie', english: 'family' },
    { dutch: 'fase', english: 'phase' },
    { dutch: 'feit', english: 'fact' },
    { dutch: 'figuur', english: 'figure' },
    { dutch: 'film', english: 'movie' },
    { dutch: 'financieel', english: 'financial' },
    { dutch: 'foto', english: 'photo' },
    { dutch: 'fruit', english: 'fruit' },
    { dutch: 'functie', english: 'function' },
    { dutch: 'fundamenteel', english: 'fundamentally' },
    { dutch: 'gaan', english: 'to go' },
    { dutch: 'gast', english: 'guest' },
    { dutch: 'geboren', english: 'born' },
    { dutch: 'geef', english: 'give' },
    { dutch: 'gemeen', english: 'mean' },
    { dutch: 'generatie', english: 'generation' },
    { dutch: 'gevoel', english: 'feeling' },
    { dutch: 'geven', english: 'to give' },
    { dutch: 'glas', english: 'glass' },
    { dutch: 'goed', english: 'good' },
    { dutch: 'goederen', english: 'goods' },
    { dutch: 'gouden', english: 'golden' },
    { dutch: 'gras', english: 'grass' },
    { dutch: 'groen', english: 'green' },
    { dutch: 'groeien', english: 'to grow' },
    { dutch: 'groep', english: 'group' },
    { dutch: 'haar', english: 'her' },
    { dutch: 'half', english: 'half' },
    { dutch: 'hand', english: 'hand' },
    { dutch: 'hard', english: 'hard' },
    { dutch: 'hart', english: 'heart' },
    { dutch: 'hebben', english: 'to have' },
    { dutch: 'heet', english: 'hot' },
    { dutch: 'helft', english: 'half' },
    { dutch: 'helpen', english: 'to help' },
    { dutch: 'hem', english: 'him' },
    { dutch: 'het', english: 'it' },
    { dutch: 'hier', english: 'here' },
    { dutch: 'hij', english: 'he' },
    { dutch: 'historisch', english: 'historical' },
    { dutch: 'hoed', english: 'hat' },
    { dutch: 'hoe', english: 'how' },
    { dutch: 'Holland', english: 'Holland' },
    { dutch: 'honger', english: 'hungry' },
    { dutch: 'hoop', english: 'hope' },
    { dutch: 'hopen', english: 'to hope' },
    { dutch: 'horen', english: 'to hear' },
    { dutch: 'hotel', english: 'hotel' },
    { dutch: 'houden', english: 'to keep' },
    { dutch: 'huis', english: 'house' },
    { dutch: 'hulp', english: 'help' },
    { dutch: 'hut', english: 'hut' },
    { dutch: 'ideaal', english: 'ideal' },
    { dutch: 'idee', english: 'idea' },
    { dutch: 'ik', english: 'I' },
    { dutch: 'in', english: 'in' },
    { dutch: 'individu', english: 'individual' },
    { dutch: 'individueel', english: 'individually' },
    { dutch: 'informatie', english: 'information' },
    { dutch: 'initiatief', english: 'initiative' },
    { dutch: 'instrument', english: 'instrument' },
    { dutch: 'interessant', english: 'interesting' },
    { dutch: 'internationaal', english: 'international' },
    { dutch: 'invloed', english: 'influence' },
    { dutch: 'ja', english: 'yes' },
    { dutch: 'jaar', english: 'year' },
    { dutch: 'je', english: 'you' },
    { dutch: 'jezelf', english: 'yourself' },
    { dutch: 'jij', english: 'you' },
    { dutch: 'jong', english: 'young' },
    { dutch: 'jongeman', english: 'young man' },
    { dutch: 'jou', english: 'you' },
    { dutch: 'jullie', english: 'you' },
    { dutch: 'juni', english: 'june' },
    { dutch: 'kaas', english: 'cheese' },
    { dutch: 'kalm', english: 'calm' },
    { dutch: 'kamp', english: 'camp' },
    { dutch: 'karakter', english: 'character' },
    { dutch: 'kat', english: 'cat' },
    { dutch: 'kilometer', english: 'kilometers' },
    { dutch: 'kind', english: 'child' },
    { dutch: 'klas', english: 'class' },
    { dutch: 'klassiek', english: 'classic' },
    { dutch: 'kleur', english: 'color' },
    { dutch: 'klimmen', english: 'to climb' },
    { dutch: 'knie', english: 'knee' },
    { dutch: 'koel', english: 'cool' },
    { dutch: 'koffie', english: 'coffee' },
    { dutch: 'komen', english: 'come' },
    { dutch: 'koning', english: 'king' },
    { dutch: 'kosten', english: 'to cost' },
    { dutch: 'koud', english: 'cold' },
    { dutch: 'kruis', english: 'cross' },
    { dutch: 'kunnen', english: 'can/to be able to' },
    { dutch: 'kust', english: 'coast' },
    { dutch: 'kwaliteit', english: 'quality' },
    { dutch: 'laat', english: 'late' },
    { dutch: 'laatste', english: 'last' },
    { dutch: 'lachen', english: 'laugh' },
    { dutch: 'landschap', english: 'landscape' },
    { dutch: 'lang', english: 'long' },
    { dutch: 'langs', english: 'along' },
    { dutch: 'laten', english: 'to let' },
    { dutch: 'later', english: 'later' },
    { dutch: 'leider', english: 'leader' },
    { dutch: 'leiden', english: 'to lead' },
    { dutch: 'leiding', english: 'leadership' },
    { dutch: 'leren', english: 'to learn' },
    { dutch: 'leven', english: 'life' },
    { dutch: 'leveren', english: 'to deliver' },
    { dutch: 'licht', english: 'light' },
    { dutch: 'liefde', english: 'love' },
    { dutch: 'lip', english: 'lip' },
    { dutch: 'literatuur', english: 'literature' },
    { dutch: 'logisch', english: 'logical' },
    { dutch: 'los', english: 'loose' },
    { dutch: 'luisteren', english: 'listen' },
    { dutch: 'luitenant', english: 'lieutenant' },
    { dutch: 'maan', english: 'moon' },
    { dutch: 'maand', english: 'month' },
    { dutch: 'maaltijd', english: 'meal' },
    { dutch: 'machine', english: 'machine' },
    { dutch: 'maken', english: 'to make' },
    { dutch: 'mama', english: 'mom' },
    { dutch: 'man', english: 'man' },
    { dutch: 'markt', english: 'market' },
    { dutch: 'materiaal', english: 'material' },
    { dutch: 'me', english: 'me' },
    { dutch: 'medisch', english: 'medical' },
    { dutch: 'meer', english: 'more' },
    { dutch: 'meester', english: 'master' },
    { dutch: 'meestal', english: 'mostly' },
    { dutch: 'menen', english: 'mean' },
    { dutch: 'meter', english: 'meter' },
    { dutch: 'methode', english: 'method' },
    { dutch: 'mezelf', english: 'myself' },
    { dutch: 'mij', english: 'me' },
    { dutch: 'mijn', english: 'my' },
    { dutch: 'miljoen', english: 'million' },
    { dutch: 'minister', english: 'minister' },
    { dutch: 'minuut', english: 'minute' },
    { dutch: 'missen', english: 'to miss' },
    { dutch: 'modern', english: 'modern' },
    { dutch: 'moeder', english: 'mother' },
    { dutch: 'moeten', english: 'should' },
    { dutch: 'moment', english: 'moment' },
    { dutch: 'mond', english: 'mouth' },
    { dutch: 'motief', english: 'motive' },
    { dutch: 'museum', english: 'museum' },
    { dutch: 'muziek', english: 'music' },
    { dutch: 'naam', english: 'name' },
    { dutch: 'nacht', english: 'night' },
    { dutch: 'nationaal', english: 'national' },
    { dutch: 'natuur', english: 'nature' },
    { dutch: 'nee', english: 'no' },
    { dutch: 'negatief', english: 'negative' },
    { dutch: 'nek', english: 'neck' },
    { dutch: 'neus', english: 'nose' },
    { dutch: 'niet', english: 'not' },
    { dutch: 'nieuw', english: 'new' },
    { dutch: 'noorden', english: 'north' },
    { dutch: 'normaal', english: 'normal' },
    { dutch: 'nu', english: 'now' },
    { dutch: 'nummer', english: 'number' },
    { dutch: 'object', english: 'object' },
    { dutch: 'of', english: 'or' },
    { dutch: 'officieel', english: 'officially' },
    { dutch: 'officier', english: 'officer' },
    { dutch: 'oktober', english: 'October' },
    { dutch: 'olie', english: 'oil' },
    { dutch: 'om', english: 'around' },
    { dutch: 'ontbreken', english: 'lack' },
    { dutch: 'oor', english: 'ear' },
    { dutch: 'open', english: 'open' },
    { dutch: 'openen', english: 'to open' },
    { dutch: 'operatie', english: 'operation' },
    { dutch: 'op', english: 'on' },
    { dutch: 'orgaan', english: 'organ' },
    { dutch: 'organisatie', english: 'organization' },
    { dutch: 'organiseren', english: 'to organize' },
    { dutch: 'oud', english: 'old' },
    { dutch: 'pad', english: 'path' },
    { dutch: 'pijn', english: 'pain' },
    { dutch: 'pijnlijk', english: 'painful' },
    { dutch: 'papier', english: 'paper' },
    { dutch: 'partner', english: 'partner' },
    { dutch: 'passeren', english: 'pass' },
    { dutch: 'patiënt', english: 'patient' },
    { dutch: 'patroon', english: 'pattern' },
    { dutch: 'periode', english: 'period' },
    { dutch: 'pers', english: 'press' },
    { dutch: 'persoon', english: 'person' },
    { dutch: 'persoonlijk', english: 'personally' },
    { dutch: 'persoonlijkheid', english: 'personality' },
    { dutch: 'plaats', english: 'place' },
    { dutch: 'plaatsen', english: 'place' },
    { dutch: 'plan', english: 'plan' },
    { dutch: 'plant', english: 'plant' },
    { dutch: 'plezier', english: 'pleasure' },
    { dutch: 'politie', english: 'law enforcement' },
    { dutch: 'positie', english: 'position' },
    { dutch: 'positief', english: 'positive' },
    { dutch: 'pot', english: 'pot' },
    { dutch: 'praktisch', english: 'practical' },
    { dutch: 'praktijk', english: 'practice' },
    { dutch: 'president', english: 'president' },
    { dutch: 'prijs', english: 'price' },
    { dutch: 'probleem', english: 'problem' },
    { dutch: 'procent', english: 'per cent' },
    { dutch: 'proces', english: 'process' },
    { dutch: 'produceren', english: 'to produce' },
    { dutch: 'productie', english: 'production' },
    { dutch: 'product', english: 'product' },
    { dutch: 'programma', english: 'program' },
    { dutch: 'project', english: 'project' },
    { dutch: 'provincie', english: 'province' },
    { dutch: 'psychologisch', english: 'psychological' },
    { dutch: 'psychologie', english: 'psychology' },
    { dutch: 'psycholoog', english: 'psychologist' },
    { dutch: 'publiceren', english: 'to publish' },
    { dutch: 'radio', english: 'radio' },
    { dutch: 'reactie', english: 'reaction' },
    { dutch: 'realiseren', english: 'realize' },
    { dutch: 'reden', english: 'reason' },
    { dutch: 'relatie', english: 'relationship' },
    { dutch: 'relatief', english: 'relatively' },
    { dutch: 'rennen', english: 'To run' },
    { dutch: 'rest', english: 'rest' },
    { dutch: 'restaurant', english: 'restaurant' },
    { dutch: 'resultaat', english: 'result' },
    { dutch: 'rijk', english: 'rich' },
    { dutch: 'risico', english: 'risk' },
    { dutch: 'rivier', english: 'river' },
    { dutch: 'rol', english: 'role' },
    { dutch: 'rond', english: 'round' },
    { dutch: 'rood', english: 'red' },
    { dutch: 'rusten', english: 'to rest' },
    { dutch: 'schaduw', english: 'shadow' },
    { dutch: 'schoen', english: 'shoe' },
    { dutch: 'school', english: 'school' },
    { dutch: 'schouder', english: 'shoulder' },
    { dutch: 'seconde', english: 'second' },
    { dutch: 'sector', english: 'sector' },
    { dutch: 'serieus', english: 'serious' },
    { dutch: 'sigaret', english: 'cigarette' },
    { dutch: 'sinds', english: 'since' },
    { dutch: 'slaap', english: 'sleep' },
    { dutch: 'slapen', english: 'to sleep' },
    { dutch: 'sneeuw', english: 'snow' },
    { dutch: 'sociaal', english: 'social' },
    { dutch: 'sommige', english: 'some' },
    { dutch: 'soms', english: 'sometimes' },
    { dutch: 'zoon', english: 'son' },
    { dutch: 'soort', english: 'kind' },
    { dutch: 'speciaal', english: 'special' },
    { dutch: 'specifiek', english: 'specific' },
    { dutch: 'spreken', english: 'to speak' },
    { dutch: 'staan', english: 'stand / to stand' },
    { dutch: 'staat', english: 'state' },
    { dutch: 'stad', english: 'city' },
    { dutch: 'stap', english: 'step' },
    { dutch: 'stappen', english: 'to step' },
    { dutch: 'station', english: 'station' },
    { dutch: 'steen', english: 'stone' },
    { dutch: 'ster', english: 'star' },
    { dutch: 'stijf', english: 'stiff' },
    { dutch: 'stijl', english: 'style' },
    { dutch: 'stoppen', english: 'stop' },
    { dutch: 'straat', english: 'street' },
    { dutch: 'structuur', english: 'structure' },
    { dutch: 'student', english: 'student' },
    { dutch: 'studeren', english: 'to study' },
    { dutch: 'studie', english: 'study' },
    { dutch: 'succes', english: 'good luck' },
    { dutch: 'suiker', english: 'sugar' },
    { dutch: 'symbool', english: 'symbol' },
    { dutch: 'systeem', english: 'system' },
    { dutch: 'tafel', english: 'table' },
    { dutch: 'tante', english: 'aunt' },
    { dutch: 'te', english: 'too' },
    { dutch: 'technisch', english: 'technical' },
    { dutch: 'techniek', english: 'technic' },
    { dutch: 'tee', english: 'tea' },
    { dutch: 'telefoon', english: 'phone' },
    { dutch: 'televisie', english: 'television' },
    { dutch: 'tekst', english: 'text' },
    { dutch: 'terug', english: 'back' },
    { dutch: 'terrein', english: 'terrain' },
    { dutch: 'terras', english: 'terrace' },
    { dutch: 'theorie', english: 'theory' },
    { dutch: 'theoretisch', english: 'theoretically' },
    { dutch: 'tien', english: 'ten' },
    { dutch: 'tijd', english: 'time' },
    { dutch: 'titel', english: 'title' },
    { dutch: 'toen', english: 'then (past)' },
    { dutch: 'tong', english: 'tongue' },
    { dutch: 'top', english: 'top' },
    { dutch: 'totaal', english: 'total' },
    { dutch: 'traditie', english: 'tradition' },
    { dutch: 'traditioneel', english: 'traditional' },
    { dutch: 'trein', english: 'train' },
    { dutch: 'twee', english: 'two' },
    { dutch: 'typisch', english: 'typical' },
    { dutch: 'u', english: 'you' },
    { dutch: 'uur', english: 'hour' },
    { dutch: 'universiteit', english: 'university' },
    { dutch: 'vader', english: 'father' },
    { dutch: 'vallen', english: 'fall' },
    { dutch: 'vechten', english: 'to fight' },
    { dutch: 'veld', english: 'field' },
    { dutch: 'ver', english: 'far' },
    { dutch: 'verbieden', english: 'to forbid' },
    { dutch: 'verder', english: 'further' },
    { dutch: 'vertellen', english: 'to tell' },
    { dutch: 'vervullen', english: 'fulfill' },
    { dutch: 'verspreiden', english: 'to spread' },
    { dutch: 'vier', english: 'four' },
    { dutch: 'vijf', english: 'five' },
    { dutch: 'vinden', english: 'find' },
    { dutch: 'vinger', english: 'finger' },
    { dutch: 'vis', english: 'fish' },
    { dutch: 'visie', english: 'vision' },
    { dutch: 'vliegen', english: 'fly' },
    { dutch: 'vloer', english: 'floor' },
    { dutch: 'vluchten', english: 'to flee' },
    { dutch: 'voet', english: 'foot' },
    { dutch: 'voelen', english: 'to feel' },
    { dutch: 'vol', english: 'full' },
    { dutch: 'voor', english: 'before' },
    { dutch: 'vorming', english: 'formation' },
    { dutch: 'vrij', english: 'free' },
    { dutch: 'vriend', english: 'friend' },
    { dutch: 'vriendelijk', english: 'friendly' },
    { dutch: 'vullen', english: 'to fill' },
    { dutch: 'vuur', english: 'fire' },
    { dutch: 'wachten', english: 'to wait' },
    { dutch: 'wakker', english: 'awake' },
    { dutch: 'wanneer', english: 'when' },
    { dutch: 'wapen', english: 'weapon' },
    { dutch: 'warm', english: 'warm' },
    { dutch: 'warmte', english: 'warmth' },
    { dutch: 'wassen', english: 'To wash' },
    { dutch: 'wat', english: 'what' },
    { dutch: 'water', english: 'water' },
    { dutch: 'we', english: 'we' },
    { dutch: 'week', english: 'week' },
    { dutch: 'welk', english: 'which' },
    { dutch: 'wens', english: 'wish' },
    { dutch: 'wensen', english: 'to wish' },
    { dutch: 'wereld', english: 'world' },
    { dutch: 'werk', english: 'work' },
    { dutch: 'werken', english: 'to work' },
    { dutch: 'westen', english: 'west' },
    { dutch: 'westers', english: 'western' },
    { dutch: 'wijd', english: 'wide' },
    { dutch: 'wij', english: 'we' },
    { dutch: 'wild', english: 'wild' },
    { dutch: 'wind', english: 'wind' },
    { dutch: 'wijn', english: 'wine' },
    { dutch: 'winnen', english: 'to win' },
    { dutch: 'winter', english: 'winter' },
    { dutch: 'wit', english: 'white' },
    { dutch: 'woord', english: 'word' },
    { dutch: 'zand', english: 'sand' },
    { dutch: 'zee', english: 'sea' },
    { dutch: 'zes', english: 'six' },
    { dutch: 'ziek', english: 'sick' },
    { dutch: 'zij', english: 'she' },
    { dutch: 'zingen', english: 'to sing' },
    { dutch: 'zitten', english: 'to sit' },
    { dutch: 'zo', english: 'so' },
    { dutch: 'zodat', english: 'so that' },
    { dutch: 'zomer', english: 'summer' },
    { dutch: 'zondag', english: 'sunday' },
    { dutch: 'zuster', english: 'sister' },
    { dutch: 'zullen', english: 'shall' }
];