export const wordList = [
  { dutch: "absoluut", english: "absolutely", level: "easy" },
  { dutch: "accepteren", english: "to accept", level: "easy" },
  { dutch: "actie", english: "action", level: "easy" },
  { dutch: "actief", english: "active", level: "easy" },
  { dutch: "activiteit", english: "activity", level: "easy" },
  { dutch: "adres", english: "address", level: "easy" },
  { dutch: "advies", english: "advice", level: "easy" },
  { dutch: "agent", english: "agent", level: "easy" },
  { dutch: "al", english: "already", level: "easy" },
  { dutch: "alle", english: "all", level: "easy" },
  { dutch: "alleen", english: "only", level: "easy" },
  { dutch: "als", english: "if/when", level: "easy" },
  { dutch: "ander", english: "other", level: "easy" },
  { dutch: "antwoord", english: "answer", level: "easy" },
  { dutch: "arm", english: "arm", level: "easy" },
  { dutch: "artikel", english: "article", level: "easy" },
  { dutch: "aspect", english: "aspect", level: "easy" },
  { dutch: "auteur", english: "author", level: "easy" },
  { dutch: "automatisch", english: "automatically", level: "easy" },
  { dutch: "baby", english: "baby", level: "easy" },
  { dutch: "baas", english: "boss", level: "easy" },
  { dutch: "bank", english: "bank", level: "easy" },
  { dutch: "basis", english: "base", level: "easy" },
  { dutch: "bed", english: "bed", level: "easy" },
  { dutch: "beide", english: "both", level: "easy" },
  { dutch: "beïnvloeden", english: "to influence", level: "easy" },
  { dutch: "begin", english: "get started", level: "easy" },
  { dutch: "beginnen", english: "to begin", level: "easy" },
  { dutch: "bespreken", english: "discuss", level: "easy" },
  { dutch: "beter", english: "better", level: "easy" },
  { dutch: "bezig", english: "busy", level: "easy" },
  { dutch: "bier", english: "beer", level: "easy" },
  { dutch: "bijten", english: "to bite", level: "easy" },
  { dutch: "bitter", english: "bitter", level: "easy" },
  { dutch: "blauw", english: "blue", level: "easy" },
  { dutch: "bloed", english: "blood", level: "easy" },
  { dutch: "bodem", english: "bottom", level: "easy" },
  { dutch: "boek", english: "book", level: "easy" },
  { dutch: "boot", english: "boat", level: "easy" },
  { dutch: "breng", english: "bring", level: "easy" },
  { dutch: "broer", english: "brother", level: "easy" },
  { dutch: "brood", english: "bread", level: "easy" },
  { dutch: "bruin", english: "brown", level: "easy" },
  { dutch: "bus", english: "bus", level: "easy" },
  { dutch: "café", english: "cafe", level: "easy" },
  { dutch: "categorie", english: "category", level: "easy" },
  { dutch: "centrum", english: "centre", level: "easy" },
  { dutch: "collega", english: "colleague", level: "easy" },
  { dutch: "combinatie", english: "combination", level: "easy" },
  { dutch: "communicatie", english: "communication", level: "easy" },
  { dutch: "computer", english: "computer", level: "easy" },
  { dutch: "conclusie", english: "conclusion", level: "easy" },
  { dutch: "consequentie", english: "consequence", level: "easy" },
  { dutch: "contact", english: "contact", level: "easy" },
  { dutch: "crisis", english: "crisis", level: "easy" },
  { dutch: "cultureel", english: "cultural", level: "easy" },
  { dutch: "cultuur", english: "culture", level: "easy" },
  { dutch: "daar", english: "there", level: "easy" },
  { dutch: "dag", english: "day", level: "easy" },
  { dutch: "dan", english: "then", level: "easy" },
  { dutch: "danken", english: "to thank", level: "easy" },
  { dutch: "dansen", english: "to dance", level: "easy" },
  { dutch: "dat", english: "that", level: "easy" },
  { dutch: "de", english: "the", level: "easy" },
  { dutch: "deel", english: "part", level: "easy" },
  { dutch: "denken", english: "to think", level: "easy" },
  { dutch: "derde", english: "third", level: "easy" },
  { dutch: "deze", english: "this", level: "easy" },
  { dutch: "diep", english: "deep", level: "easy" },
  { dutch: "ding", english: "thing", level: "easy" },
  { dutch: "direct", english: "directly", level: "easy" },
  { dutch: "directeur", english: "director", level: "easy" },
  { dutch: "discussie", english: "discussion", level: "easy" },
  { dutch: "dit", english: "this", level: "easy" },
  { dutch: "dochter", english: "daughter", level: "easy" },
  { dutch: "doen", english: "to do", level: "easy" },
  { dutch: "dokter", english: "doctor", level: "easy" },
  { dutch: "dom", english: "dumb", level: "easy" },
  { dutch: "dood (zelfst. nw.)", english: "death", level: "easy" },
  { dutch: "dood (bijv. nw.)", english: "dead", level: "easy" },
  { dutch: "door", english: "door", level: "easy" },
  { dutch: "drie", english: "three", level: "easy" },
  { dutch: "drinken", english: "drink", level: "easy" },
  { dutch: "dromen", english: "to dream", level: "easy" },
  { dutch: "droom", english: "dream", level: "easy" },
  { dutch: "dubbel", english: "double", level: "easy" },
  { dutch: "dun", english: "thin", level: "easy" },
  { dutch: "economie", english: "economy", level: "easy" },
  { dutch: "een", english: "a", level: "easy" },
  { dutch: "eerst", english: "first", level: "easy" },
  { dutch: "effect", english: "effect", level: "easy" },
  { dutch: "eind", english: "end", level: "easy" },
  { dutch: "eindeloos", english: "endless", level: "easy" },
  { dutch: "eindigen", english: "to end", level: "easy" },
  { dutch: "eiland", english: "island", level: "easy" },
  { dutch: "ei", english: "egg", level: "easy" },
  { dutch: "elk", english: "each", level: "easy" },
  { dutch: "emotie", english: "emotion", level: "easy" },
  { dutch: "emotioneel", english: "emotional", level: "easy" },
  { dutch: "en", english: "and", level: "easy" },
  { dutch: "energie", english: "energy", level: "easy" },
  { dutch: "Engels", english: "english", level: "easy" },
  { dutch: "enorm", english: "enormous", level: "easy" },
  { dutch: "er", english: "there", level: "easy" },
  { dutch: "experiment", english: "experiment", level: "easy" },
  { dutch: "fabriek", english: "factory", level: "easy" },
  { dutch: "factor", english: "factor", level: "easy" },
  { dutch: "familie", english: "family", level: "easy" },
  { dutch: "fase", english: "phase", level: "easy" },
  { dutch: "feit", english: "fact", level: "easy" },
  { dutch: "figuur", english: "figure", level: "easy" },
  { dutch: "film", english: "movie", level: "easy" },
  { dutch: "financieel", english: "financial", level: "easy" },
  { dutch: "foto", english: "photo", level: "easy" },
  { dutch: "fruit", english: "fruit", level: "easy" },
  { dutch: "functie", english: "function", level: "easy" },
  { dutch: "fundamenteel", english: "fundamentally", level: "easy" },
  { dutch: "gaan", english: "to go", level: "easy" },
  { dutch: "gast", english: "guest", level: "easy" },
  { dutch: "geboren", english: "born", level: "easy" },
  { dutch: "geef", english: "give", level: "easy" },
  { dutch: "gemeen", english: "mean", level: "easy" },
  { dutch: "generatie", english: "generation", level: "easy" },
  { dutch: "gevoel", english: "feeling", level: "easy" },
  { dutch: "geven", english: "to give", level: "easy" },
  { dutch: "glas", english: "glass", level: "easy" },
  { dutch: "goed", english: "good", level: "easy" },
  { dutch: "goederen", english: "goods", level: "easy" },
  { dutch: "gouden", english: "golden", level: "easy" },
  { dutch: "gras", english: "grass", level: "easy" },
  { dutch: "groen", english: "green", level: "easy" },
  { dutch: "groeien", english: "to grow", level: "easy" },
  { dutch: "groep", english: "group", level: "easy" },
  { dutch: "haar", english: "her", level: "easy" },
  { dutch: "half", english: "half", level: "easy" },
  { dutch: "hand", english: "hand", level: "easy" },
  { dutch: "hard", english: "hard", level: "easy" },
  { dutch: "hart", english: "heart", level: "easy" },
  { dutch: "hebben", english: "to have", level: "easy" },
  { dutch: "heet", english: "hot", level: "easy" },
  { dutch: "helft", english: "half", level: "easy" },
  { dutch: "helpen", english: "to help", level: "easy" },
  { dutch: "hem", english: "him", level: "easy" },
  { dutch: "het", english: "it", level: "easy" },
  { dutch: "hier", english: "here", level: "easy" },
  { dutch: "hij", english: "he", level: "easy" },
  { dutch: "historisch", english: "historical", level: "easy" },
  { dutch: "hoed", english: "hat", level: "easy" },
  { dutch: "hoe", english: "how", level: "easy" },
  { dutch: "Holland", english: "Holland", level: "easy" },
  { dutch: "honger", english: "hungry", level: "easy" },
  { dutch: "hoop", english: "hope", level: "easy" },
  { dutch: "hopen", english: "to hope", level: "easy" },
  { dutch: "horen", english: "to hear", level: "easy" },
  { dutch: "hotel", english: "hotel", level: "easy" },
  { dutch: "houden", english: "to keep", level: "easy" },
  { dutch: "huis", english: "house", level: "easy" },
  { dutch: "hulp", english: "help", level: "easy" },
  { dutch: "hut", english: "hut", level: "easy" },
  { dutch: "ideaal", english: "ideal", level: "easy" },
  { dutch: "idee", english: "idea", level: "easy" },
  { dutch: "ik", english: "I", level: "easy" },
  { dutch: "in", english: "in", level: "easy" },
  { dutch: "individu", english: "individual", level: "easy" },
  { dutch: "individueel", english: "individually", level: "easy" },
  { dutch: "informatie", english: "information", level: "easy" },
  { dutch: "initiatief", english: "initiative", level: "easy" },
  { dutch: "instrument", english: "instrument", level: "easy" },
  { dutch: "interessant", english: "interesting", level: "easy" },
  { dutch: "internationaal", english: "international", level: "easy" },
  { dutch: "invloed", english: "influence", level: "easy" },
  { dutch: "ja", english: "yes", level: "easy" },
  { dutch: "jaar", english: "year", level: "easy" },
  { dutch: "je", english: "you", level: "easy" },
  { dutch: "jezelf", english: "yourself", level: "easy" },
  { dutch: "jij", english: "you", level: "easy" },
  { dutch: "jong", english: "young", level: "easy" },
  { dutch: "jongeman", english: "young man", level: "easy" },
  { dutch: "jou", english: "you", level: "easy" },
  { dutch: "jullie", english: "you", level: "easy" },
  { dutch: "juni", english: "june", level: "easy" },
  { dutch: "kaas", english: "cheese", level: "easy" },
  { dutch: "kalm", english: "calm", level: "easy" },
  { dutch: "kamp", english: "camp", level: "easy" },
  { dutch: "karakter", english: "character", level: "easy" },
  { dutch: "kat", english: "cat", level: "easy" },
  { dutch: "kilometer", english: "kilometers", level: "easy" },
  { dutch: "kind", english: "child", level: "easy" },
  { dutch: "klas", english: "class", level: "easy" },
  { dutch: "klassiek", english: "classic", level: "easy" },
  { dutch: "kleur", english: "color", level: "easy" },
  { dutch: "klimmen", english: "to climb", level: "easy" },
  { dutch: "knie", english: "knee", level: "easy" },
  { dutch: "koel", english: "cool", level: "easy" },
  { dutch: "koffie", english: "coffee", level: "easy" },
  { dutch: "komen", english: "come", level: "easy" },
  { dutch: "koning", english: "king", level: "easy" },
  { dutch: "kosten", english: "to cost", level: "easy" },
  { dutch: "koud", english: "cold", level: "easy" },
  { dutch: "kruis", english: "cross", level: "easy" },
  { dutch: "kunnen", english: "can/to be able to", level: "easy" },
  { dutch: "kust", english: "coast", level: "easy" },
  { dutch: "kwaliteit", english: "quality", level: "easy" },
  { dutch: "laat", english: "late", level: "easy" },
  { dutch: "laatste", english: "last", level: "easy" },
  { dutch: "lachen", english: "laugh", level: "easy" },
  { dutch: "landschap", english: "landscape", level: "easy" },
  { dutch: "lang", english: "long", level: "easy" },
  { dutch: "langs", english: "along", level: "easy" },
  { dutch: "laten", english: "to let", level: "easy" },
  { dutch: "later", english: "later", level: "easy" },
  { dutch: "leider", english: "leader", level: "easy" },
  { dutch: "leiden", english: "to lead", level: "easy" },
  { dutch: "leiding", english: "leadership", level: "easy" },
  { dutch: "leren", english: "to learn", level: "easy" },
  { dutch: "leven", english: "life", level: "easy" },
  { dutch: "leveren", english: "to deliver", level: "easy" },
  { dutch: "licht", english: "light", level: "easy" },
  { dutch: "liefde", english: "love", level: "easy" },
  { dutch: "lip", english: "lip", level: "easy" },
  { dutch: "literatuur", english: "literature", level: "easy" },
  { dutch: "logisch", english: "logical", level: "easy" },
  { dutch: "los", english: "loose", level: "easy" },
  { dutch: "luisteren", english: "listen", level: "easy" },
  { dutch: "luitenant", english: "lieutenant", level: "easy" },
  { dutch: "maan", english: "moon", level: "easy" },
  { dutch: "maand", english: "month", level: "easy" },
  { dutch: "maaltijd", english: "meal", level: "easy" },
  { dutch: "machine", english: "machine", level: "easy" },
  { dutch: "maken", english: "to make", level: "easy" },
  { dutch: "mama", english: "mom", level: "easy" },
  { dutch: "man", english: "man", level: "easy" },
  { dutch: "markt", english: "market", level: "easy" },
  { dutch: "materiaal", english: "material", level: "easy" },
  { dutch: "me", english: "me", level: "easy" },
  { dutch: "medisch", english: "medical", level: "easy" },
  { dutch: "meer", english: "more", level: "easy" },
  { dutch: "meester", english: "master", level: "easy" },
  { dutch: "meestal", english: "mostly", level: "easy" },
  { dutch: "menen", english: "mean", level: "easy" },
  { dutch: "meter", english: "meter", level: "easy" },
  { dutch: "methode", english: "method", level: "easy" },
  { dutch: "mezelf", english: "myself", level: "easy" },
  { dutch: "mij", english: "me", level: "easy" },
  { dutch: "mijn", english: "my", level: "easy" },
  { dutch: "miljoen", english: "million", level: "easy" },
  { dutch: "minister", english: "minister", level: "easy" },
  { dutch: "minuut", english: "minute", level: "easy" },
  { dutch: "missen", english: "to miss", level: "easy" },
  { dutch: "modern", english: "modern", level: "easy" },
  { dutch: "moeder", english: "mother", level: "easy" },
  { dutch: "moeten", english: "should", level: "easy" },
  { dutch: "moment", english: "moment", level: "easy" },
  { dutch: "mond", english: "mouth", level: "easy" },
  { dutch: "motief", english: "motive", level: "easy" },
  { dutch: "museum", english: "museum", level: "easy" },
  { dutch: "muziek", english: "music", level: "easy" },
  { dutch: "naam", english: "name", level: "easy" },
  { dutch: "nacht", english: "night", level: "easy" },
  { dutch: "nationaal", english: "national", level: "easy" },
  { dutch: "natuur", english: "nature", level: "easy" },
  { dutch: "nee", english: "no", level: "easy" },
  { dutch: "negatief", english: "negative", level: "easy" },
  { dutch: "nek", english: "neck", level: "easy" },
  { dutch: "neus", english: "nose", level: "easy" },
  { dutch: "niet", english: "not", level: "easy" },
  { dutch: "nieuw", english: "new", level: "easy" },
  { dutch: "noorden", english: "north", level: "easy" },
  { dutch: "normaal", english: "normal", level: "easy" },
  { dutch: "nu", english: "now", level: "easy" },
  { dutch: "nummer", english: "number", level: "easy" },
  { dutch: "object", english: "object", level: "easy" },
  { dutch: "of", english: "or", level: "easy" },
  { dutch: "officieel", english: "officially", level: "easy" },
  { dutch: "officier", english: "officer", level: "easy" },
  { dutch: "oktober", english: "October", level: "easy" },
  { dutch: "olie", english: "oil", level: "easy" },
  { dutch: "om", english: "around", level: "easy" },
  { dutch: "ontbreken", english: "lack", level: "easy" },
  { dutch: "oor", english: "ear", level: "easy" },
  { dutch: "open", english: "open", level: "easy" },
  { dutch: "openen", english: "to open", level: "easy" },
  { dutch: "operatie", english: "operation", level: "easy" },
  { dutch: "op", english: "on", level: "easy" },
  { dutch: "orgaan", english: "organ", level: "easy" },
  { dutch: "organisatie", english: "organization", level: "easy" },
  { dutch: "organiseren", english: "to organize", level: "easy" },
  { dutch: "oud", english: "old", level: "easy" },
  { dutch: "pijnlijk", english: "painful", difficulty: "easy" },
  { dutch: "papier", english: "paper", difficulty: "easy" },
  { dutch: "partner", english: "partner", difficulty: "easy" },
  { dutch: "passeren", english: "pass", difficulty: "easy" },
  { dutch: "patiënt", english: "patient", difficulty: "easy" },
  { dutch: "patroon", english: "pattern", difficulty: "easy" },
  { dutch: "periode", english: "period", difficulty: "easy" },
  { dutch: "pers", english: "press", difficulty: "easy" },
  { dutch: "persoon", english: "person", difficulty: "easy" },
  { dutch: "persoonlijk", english: "personally", difficulty: "easy" },
  { dutch: "persoonlijkheid", english: "personality", difficulty: "easy" },
  { dutch: "plaats", english: "place", difficulty: "easy" },
  { dutch: "plaatsen", english: "place", difficulty: "easy" },
  { dutch: "plan", english: "plan", difficulty: "easy" },
  { dutch: "plant", english: "plant", difficulty: "easy" },
  { dutch: "plezier", english: "pleasure", difficulty: "easy" },
  { dutch: "politie", english: "law enforcement", difficulty: "easy" },
  { dutch: "positie", english: "position", difficulty: "easy" },
  { dutch: "positief", english: "positive", difficulty: "easy" },
  { dutch: "pot", english: "pot", difficulty: "easy" },
  { dutch: "praktisch", english: "practical", difficulty: "easy" },
  { dutch: "praktijk", english: "practice", difficulty: "easy" },
  { dutch: "president", english: "president", difficulty: "easy" },
  { dutch: "prijs", english: "price", difficulty: "easy" },
  { dutch: "probleem", english: "problem", difficulty: "easy" },
  { dutch: "procent", english: "per cent", difficulty: "easy" },
  { dutch: "proces", english: "process", difficulty: "easy" },
  { dutch: "produceren", english: "to produce", difficulty: "easy" },
  { dutch: "productie", english: "production", difficulty: "easy" },
  { dutch: "product", english: "product", difficulty: "easy" },
  { dutch: "programma", english: "program", difficulty: "easy" },
  { dutch: "project", english: "project", difficulty: "easy" },
  { dutch: "provincie", english: "province", difficulty: "easy" },
  { dutch: "psychologisch", english: "psychological", difficulty: "easy" },
  { dutch: "psychologie", english: "psychology", difficulty: "easy" },
  { dutch: "psycholoog", english: "psychologist", difficulty: "easy" },
  { dutch: "publiceren", english: "to publish", difficulty: "easy" },
  { dutch: "radio", english: "radio", difficulty: "easy" },
  { dutch: "reactie", english: "reaction", difficulty: "easy" },
  { dutch: "realiseren", english: "realize", difficulty: "easy" },
  { dutch: "reden", english: "reason", difficulty: "easy" },
  { dutch: "relatie", english: "relationship", difficulty: "easy" },
  { dutch: "relatief", english: "relatively", difficulty: "easy" },
  { dutch: "rennen", english: "To run", difficulty: "easy" },
  { dutch: "rest", english: "rest", difficulty: "easy" },
  { dutch: "restaurant", english: "restaurant", difficulty: "easy" },
  { dutch: "resultaat", english: "result", difficulty: "easy" },
  { dutch: "rijk", english: "rich", difficulty: "easy" },
  { dutch: "risico", english: "risk", difficulty: "easy" },
  { dutch: "rivier", english: "river", difficulty: "easy" },
  { dutch: "rol", english: "role", difficulty: "easy" },
  { dutch: "rond", english: "round", difficulty: "easy" },
  { dutch: "rood", english: "red", difficulty: "easy" },
  { dutch: "rusten", english: "to rest", difficulty: "easy" },
  { dutch: "schaduw", english: "shadow", difficulty: "easy" },
  { dutch: "schoen", english: "shoe", difficulty: "easy" },
  { dutch: "school", english: "school", difficulty: "easy" },
  { dutch: "schouder", english: "shoulder", difficulty: "easy" },
  { dutch: "seconde", english: "second", difficulty: "easy" },
  { dutch: "sector", english: "sector", difficulty: "easy" },
  { dutch: "serieus", english: "serious", difficulty: "easy" },
  { dutch: "sigaret", english: "cigarette", difficulty: "easy" },
  { dutch: "sinds", english: "since", difficulty: "easy" },
  { dutch: "slaap", english: "sleep", difficulty: "easy" },
  { dutch: "slapen", english: "to sleep", difficulty: "easy" },
  { dutch: "sneeuw", english: "snow", difficulty: "easy" },
  { dutch: "sociaal", english: "social", difficulty: "easy" },
  { dutch: "sommige", english: "some", difficulty: "easy" },
  { dutch: "soms", english: "sometimes", difficulty: "easy" },
  { dutch: "soort", english: "kind", difficulty: "easy" },
  { dutch: "speciaal", english: "special", difficulty: "easy" },
  { dutch: "specifiek", english: "specific", difficulty: "easy" },
  { dutch: "spreken", english: "to speak", difficulty: "easy" },
  { dutch: "staan", english: "stand / to stand", difficulty: "easy" },
  { dutch: "staat", english: "state", difficulty: "easy" },
  { dutch: "stad", english: "city", difficulty: "easy" },
  { dutch: "stap", english: "step", difficulty: "easy" },
  { dutch: "stappen", english: "to step", difficulty: "easy" },
  { dutch: "station", english: "station", difficulty: "easy" },
  { dutch: "steen", english: "stone", difficulty: "easy" },
  { dutch: "ster", english: "star", difficulty: "easy" },
  { dutch: "stijf", english: "stiff", difficulty: "easy" },
  { dutch: "stijl", english: "style", difficulty: "easy" },
  { dutch: "stoppen", english: "stop", difficulty: "easy" },
  { dutch: "straat", english: "street", difficulty: "easy" },
  { dutch: "structuur", english: "structure", difficulty: "easy" },
  { dutch: "student", english: "student", difficulty: "easy" },
  { dutch: "studeren", english: "to study", difficulty: "easy" },
  { dutch: "studie", english: "study", difficulty: "easy" },
  { dutch: "succes", english: "good luck", difficulty: "easy" },
  { dutch: "suiker", english: "sugar", difficulty: "easy" },
  { dutch: "symbool", english: "symbol", difficulty: "easy" },
  { dutch: "systeem", english: "system", difficulty: "easy" },
  { dutch: "tafel", english: "table", difficulty: "easy" },
  { dutch: "tante", english: "aunt", difficulty: "easy" },
  { dutch: "te", english: "too", difficulty: "easy" },
  { dutch: "technisch", english: "technical", difficulty: "easy" },
  { dutch: "techniek", english: "technic", difficulty: "easy" },
  { dutch: "tee", english: "tea", difficulty: "easy" },
  { dutch: "telefoon", english: "phone", difficulty: "easy" },
  { dutch: "televisie", english: "television", difficulty: "easy" },
  { dutch: "tekst", english: "text", difficulty: "easy" },
  { dutch: "terug", english: "back", difficulty: "easy" },
  { dutch: "terrein", english: "terrain", difficulty: "easy" },
  { dutch: "terras", english: "terrace", difficulty: "easy" },
  { dutch: "theorie", english: "theory", difficulty: "easy" },
  { dutch: "theoretisch", english: "theoretically", difficulty: "easy" },
  { dutch: "tien", english: "ten", difficulty: "easy" },
  { dutch: "tijd", english: "time", difficulty: "easy" },
  { dutch: "titel", english: "title", difficulty: "easy" },
  { dutch: "toen", english: "then (past)", difficulty: "easy" },
  { dutch: "tong", english: "tongue", difficulty: "easy" },
  { dutch: "top", english: "top", difficulty: "easy" },
  { dutch: "totaal", english: "total", difficulty: "easy" },
  { dutch: "traditie", english: "tradition", difficulty: "easy" },
  { dutch: "traditioneel", english: "traditional", difficulty: "easy" },
  { dutch: "trein", english: "train", difficulty: "easy" },
  { dutch: "twee", english: "two", difficulty: "easy" },
  { dutch: "typisch", english: "typical", difficulty: "easy" },
  { dutch: "u", english: "you", difficulty: "easy" },
  { dutch: "uur", english: "hour", difficulty: "easy" },
  { dutch: "universiteit", english: "university", difficulty: "easy" },
  { dutch: "vader", english: "father", difficulty: "easy" },
  { dutch: "vallen", english: "fall", difficulty: "easy" },
  { dutch: "vechten", english: "to fight", difficulty: "easy" },
  { dutch: "veld", english: "field", difficulty: "easy" },
  { dutch: "ver", english: "far", difficulty: "easy" },
  { dutch: "verbieden", english: "to forbid", difficulty: "easy" },
  { dutch: "verder", english: "further", difficulty: "easy" },
  { dutch: "vertellen", english: "to tell", difficulty: "easy" },
  { dutch: "vervullen", english: "fulfill", difficulty: "easy" },
  { dutch: "verspreiden", english: "to spread", difficulty: "easy" },
  { dutch: "vier", english: "four", difficulty: "easy" },
  { dutch: "vijf", english: "five", difficulty: "easy" },
  { dutch: "vinden", english: "find", difficulty: "easy" },
  { dutch: "vinger", english: "finger", difficulty: "easy" },
  { dutch: "vis", english: "fish", difficulty: "easy" },
  { dutch: "visie", english: "vision", difficulty: "easy" },
  { dutch: "vliegen", english: "fly", difficulty: "easy" },
  { dutch: "vloer", english: "floor", difficulty: "easy" },
  { dutch: "vluchten", english: "to flee", difficulty: "easy" },
  { dutch: "voet", english: "foot", difficulty: "easy" },
  { dutch: "voelen", english: "to feel", difficulty: "easy" },
  { dutch: "vol", english: "full", difficulty: "easy" },
  { dutch: "voor", english: "before", difficulty: "easy" },
  { dutch: "vorming", english: "formation", difficulty: "easy" },
  { dutch: "vrij", english: "free", difficulty: "easy" },
  { dutch: "vriend", english: "friend", difficulty: "easy" },
  { dutch: "vriendelijk", english: "friendly", difficulty: "easy" },
  { dutch: "vullen", english: "to fill", difficulty: "easy" },
  { dutch: "vuur", english: "fire", difficulty: "easy" },
  { dutch: "wachten", english: "to wait", difficulty: "easy" },
  { dutch: "wakker", english: "awake", difficulty: "easy" },
  { dutch: "wanneer", english: "when", difficulty: "easy" },
  { dutch: "wapen", english: "weapon", difficulty: "easy" },
  { dutch: "warm", english: "warm", difficulty: "easy" },
  { dutch: "warmte", english: "warmth", difficulty: "easy" },
  { dutch: "water", english: "water", difficulty: "easy" },
  { dutch: "week", english: "week", difficulty: "easy" },
  { dutch: "weg", english: "road", difficulty: "easy" },
  { dutch: "wel", english: "well", difficulty: "easy" },
  { dutch: "werk", english: "work", difficulty: "easy" },
  { dutch: "werken", english: "to work", difficulty: "easy" },
  { dutch: "wereld", english: "world", difficulty: "easy" },
  { dutch: "wet", english: "law", difficulty: "easy" },
  { dutch: "wetenschap", english: "science", difficulty: "easy" },
  { dutch: "wetenschappelijk", english: "scientific", difficulty: "easy" },
  { dutch: "wie", english: "who", difficulty: "easy" },
  { dutch: "wijn", english: "wine", difficulty: "easy" },
  { dutch: "wij", english: "we", difficulty: "easy" },
  { dutch: "willen", english: "to want", difficulty: "easy" },
  { dutch: "wind", english: "wind", difficulty: "easy" },
  { dutch: "winkel", english: "shop", difficulty: "easy" },
  { dutch: "woord", english: "word", difficulty: "easy" },
  { dutch: "woordenboek", english: "dictionary", difficulty: "easy" },
  { dutch: "wonen", english: "to live", difficulty: "easy" },
  { dutch: "woning", english: "residence", difficulty: "easy" },
  { dutch: "woud", english: "forest", difficulty: "easy" },
  { dutch: "wraak", english: "revenge", difficulty: "easy" },
  { dutch: "wrijven", english: "to rub", difficulty: "easy" },
  { dutch: "zacht", english: "soft", difficulty: "easy" },
  { dutch: "zak", english: "bag", difficulty: "easy" },
  { dutch: "zand", english: "sand", difficulty: "easy" },
  { dutch: "ze", english: "they", difficulty: "easy" },
  { dutch: "zee", english: "sea", difficulty: "easy" },
  { dutch: "zeggen", english: "to say", difficulty: "easy" },
  { dutch: "zelf", english: "self", difficulty: "easy" },
  { dutch: "zeker", english: "sure", difficulty: "easy" },
  { dutch: "zelfstandig", english: "independent", difficulty: "easy" },
  { dutch: "zender", english: "transmitter", difficulty: "easy" },
  { dutch: "zetten", english: "to put", difficulty: "easy" },
  { dutch: "zich", english: "himself/herself", difficulty: "easy" },
  { dutch: "ziek", english: "sick", difficulty: "easy" },
  { dutch: "zien", english: "to see", difficulty: "easy" },
  { dutch: "zilver", english: "silver", difficulty: "easy" },
  { dutch: "zingen", english: "to sing", difficulty: "easy" },
  { dutch: "zin", english: "sentence", difficulty: "easy" },
  { dutch: "zitten", english: "to sit", difficulty: "easy" },
  { dutch: "zo", english: "so", difficulty: "easy" },
  { dutch: "zoeken", english: "to search", difficulty: "easy" },
  { dutch: "zoet", english: "sweet", difficulty: "easy" },
  { dutch: "zomer", english: "summer", difficulty: "easy" },
  { dutch: "zon", english: "sun", difficulty: "easy" },
  { dutch: "zonder", english: "without", difficulty: "easy" },
  { dutch: "zorg", english: "care", difficulty: "easy" },
  { dutch: "zorgen", english: "to care", difficulty: "easy" },
  { dutch: "zout", english: "salt", difficulty: "easy" },
  { dutch: "zowel", english: "as well as", difficulty: "easy" },
  { dutch: "zullen", english: "shall", difficulty: "easy" },
  { dutch: "zus", english: "sister", difficulty: "easy" },
  { dutch: "zwart", english: "black", difficulty: "easy" },
  { dutch: "zwemmen", english: "to swim", difficulty: "easy" },
  { dutch: "boom", english: "tree", difficulty: "medium" },
  { dutch: "stoel", english: "chair", difficulty: "medium" },
  { dutch: "van", english: "from / of", difficulty: "medium" },
  { dutch: "zijn", english: "to be", difficulty: "medium" },
  { dutch: "met", english: "with", difficulty: "medium" },
  { dutch: "als", english: "if/when", difficulty: "medium" },
  { dutch: "er", english: "there", difficulty: "medium" },
  { dutch: "maar", english: "but", difficulty: "medium" },
  { dutch: "om", english: "around", difficulty: "medium" },
  { dutch: "naar", english: "to", difficulty: "medium" },
  { dutch: "ook", english: "also", difficulty: "medium" },
  { dutch: "bij", english: "at", difficulty: "medium" },
  { dutch: "nog", english: "yet", difficulty: "medium" },
  { dutch: "tot", english: "until", difficulty: "medium" },
  { dutch: "ons/onze", english: "our", difficulty: "medium" },
  { dutch: "veel", english: "many", difficulty: "medium" },
  { dutch: "mens", english: "human", difficulty: "medium" },
  { dutch: "toch", english: "however", difficulty: "medium" },
  { dutch: "na", english: "after", difficulty: "medium" },
  { dutch: "tijd", english: "time", difficulty: "medium" },
  { dutch: "kind", english: "child", difficulty: "medium" },
  { dutch: "vrouw", english: "woman", difficulty: "medium" },
  { dutch: "oog", english: "eye", difficulty: "medium" },
  { dutch: "dus", english: "so", difficulty: "medium" },
  { dutch: "heel", english: "very", difficulty: "medium" },
  { dutch: "even", english: "for a bit, for a while", difficulty: "medium" },
  { dutch: "zelfs", english: "even", difficulty: "medium" },
  { dutch: "elk", english: "each", difficulty: "medium" },
  { dutch: "ver", english: "far", difficulty: "medium" },
  { dutch: "hoofd", english: "head", difficulty: "medium" },
  { dutch: "zeer, heel", english: "very", difficulty: "medium" },
  { dutch: "een paar", english: "a couple", difficulty: "medium" },
  { dutch: "vraag", english: "question", difficulty: "medium" },
  { dutch: "vaak", english: "often", difficulty: "medium" },
  { dutch: "keer", english: "times", difficulty: "medium" },
  { dutch: "eerst", english: "first", difficulty: "medium" },
  { dutch: "weg", english: "away", difficulty: "medium" },
  { dutch: "zaak", english: "matter, business", difficulty: "medium" },
  { dutch: "net", english: "just", difficulty: "medium" },
  { dutch: "heen", english: "away", difficulty: "medium" },
  { dutch: "hoog", english: "high", difficulty: "medium" },
  { dutch: "juist", english: "right", difficulty: "medium" },
  { dutch: "sterk", english: "strong", difficulty: "medium" },
  { dutch: "waar", english: "true", difficulty: "medium" },
  { dutch: "deel", english: "part", difficulty: "medium" },
  { dutch: "snel", english: "fast", difficulty: "medium" },
  { dutch: "mooi", english: "beautiful, pretty", difficulty: "medium" },
  { dutch: "feit", english: "fact", difficulty: "medium" },
  { dutch: "zin", english: "sentence", difficulty: "medium" },
  { dutch: "kort", english: "short", difficulty: "medium" },
  { dutch: "vast", english: "fixed", difficulty: "medium" },
  { dutch: "stad", english: "city", difficulty: "medium" },
  { dutch: "vroeg", english: "early", difficulty: "medium" },
  { dutch: "stem", english: "voice", difficulty: "medium" },
  { dutch: "kant", english: "side", difficulty: "medium" },
  { dutch: "geld", english: "money", difficulty: "medium" },
  { dutch: "stuk", english: "piece", difficulty: "medium" },
  { dutch: "graag", english: "gladly", difficulty: "medium" },
  { dutch: "nou", english: "well", difficulty: "medium" },
  { dutch: "pas", english: "only", difficulty: "medium" },
  { dutch: "recht", english: "straight", difficulty: "medium" },
  { dutch: "zwaar", english: "heavy", difficulty: "medium" },
  { dutch: "lid", english: "member", difficulty: "medium" },
  { dutch: "eeuw", english: "century", difficulty: "medium" },
  { dutch: "mond", english: "mouth", difficulty: "medium" },
  { dutch: "opnieuw", english: "again", difficulty: "medium" },
  { dutch: "thuis", english: "at home", difficulty: "medium" },
  { dutch: "kracht", english: "power", difficulty: "medium" },
  { dutch: "ooit", english: "ever", difficulty: "medium" },
  { dutch: "kerk", english: "church", difficulty: "medium" },
  { dutch: "blik", english: "look", difficulty: "medium" },
  { dutch: "kans", english: "opportunity", difficulty: "medium" },
  { dutch: "brief", english: "letter", difficulty: "medium" },
  { dutch: "beeld", english: "statue", difficulty: "medium" },
  { dutch: "zacht", english: "soft", difficulty: "medium" },
  { dutch: "macht", english: "power", difficulty: "medium" },
  { dutch: "via / door", english: "through", difficulty: "medium" },
  { dutch: "gang", english: "corridor", difficulty: "medium" },
  { dutch: "been", english: "leg", difficulty: "medium" },
  { dutch: "slecht", english: "bad", difficulty: "medium" },
  { dutch: "wet", english: "law", difficulty: "medium" },
  { dutch: "bang", english: "afraid", difficulty: "medium" },
  { dutch: "dier", english: "animal", difficulty: "medium" },
  { dutch: "lucht", english: "sky", difficulty: "medium" },
  { dutch: "rug", english: "back", difficulty: "medium" },
  { dutch: "angst", english: "fear", difficulty: "medium" },
  { dutch: "laag", english: "low", difficulty: "medium" },
  { dutch: "raam", english: "window", difficulty: "medium" },
  { dutch: "hond", english: "dog", difficulty: "medium" },
  { dutch: "stil", english: "quiet", difficulty: "medium" },
  { dutch: "doel", english: "target", difficulty: "medium" },
  { dutch: "dienst", english: "shift", difficulty: "medium" },
  { dutch: "zwart", english: "black", difficulty: "medium" },
  { dutch: "menen", english: "mean", difficulty: "medium" },
  { dutch: "dik", english: "fat", difficulty: "medium" },
  { dutch: "paard", english: "horse", difficulty: "medium" },
  { dutch: "vreemd", english: "strange", difficulty: "medium" },
  { dutch: "taal", english: "language", difficulty: "medium" },
  { dutch: "volk", english: "people", difficulty: "medium" },
  { dutch: "aarde", english: "soil", difficulty: "medium" },
  { dutch: "stoel", english: "chair", difficulty: "medium" },
  { dutch: "muur", english: "wall", difficulty: "medium" },
  { dutch: "raad", english: "advice", difficulty: "medium" },
  { dutch: "boom", english: "tree", difficulty: "medium" },
  { dutch: "dorp", english: "village", difficulty: "medium" },
  { dutch: "breed", english: "wide", difficulty: "medium" },
  { dutch: "leeg", english: "empty", difficulty: "medium" },
  { dutch: "lief", english: "sweet", difficulty: "medium" },
  { dutch: "klaar", english: "ready", difficulty: "medium" },
  { dutch: "zorg", english: "care", difficulty: "medium" },
  { dutch: "gauw", english: "soon", difficulty: "medium" },
  { dutch: "trap", english: "stairs", difficulty: "medium" },
  { dutch: "gek", english: "crazy", difficulty: "medium" },
  { dutch: "blad", english: "sheet", difficulty: "medium" },
  { dutch: "spel", english: "game", difficulty: "medium" },
  { dutch: "zak", english: "bag", difficulty: "medium" },
  { dutch: "borst", english: "chest", difficulty: "medium" },
  { dutch: "hoop", english: "pile", difficulty: "medium" },
  { dutch: "fles", english: "bottle", difficulty: "medium" },
  { dutch: "grens", english: "border", difficulty: "medium" },
  { dutch: "hoek", english: "corner", difficulty: "medium" },
  { dutch: "oom", english: "uncle", difficulty: "medium" },
  { dutch: "vlak", english: "flat", difficulty: "medium" },
  { dutch: "buurt", english: "neighborhood", difficulty: "medium" },
  { dutch: "ruim", english: "spacious", difficulty: "medium" },
  { dutch: "blij", english: "happy", difficulty: "medium" },
  { dutch: "eten", english: "food", difficulty: "medium" },
  { dutch: "stof", english: "dust", difficulty: "medium" },
  { dutch: "gat", english: "hole", difficulty: "medium" },
  { dutch: "boer", english: "farmer", difficulty: "medium" },
  { dutch: "reis", english: "trip, journey", difficulty: "medium" },
  { dutch: "druk", english: "busy", difficulty: "medium" },
  { dutch: "druk", english: "pressure", difficulty: "medium" },
  { dutch: "vlug / snel", english: "quickly", difficulty: "medium" },
  { dutch: "schuld", english: "debt", difficulty: "medium" },
  { dutch: "leuk", english: "fun", difficulty: "medium" },
  { dutch: "bloem", english: "flower", difficulty: "medium" },
  { dutch: "huisarts", english: "doctor", difficulty: "medium" },
  { dutch: "fijn", english: "nice", difficulty: "medium" },
  { dutch: "links", english: "left", difficulty: "medium" },
  { dutch: "plek", english: "place", difficulty: "medium" },
  { dutch: "niks", english: "nothing", difficulty: "medium" },
  { dutch: "tand", english: "tooth", difficulty: "medium" },
  { dutch: "rand", english: "edge", difficulty: "medium" },
  { dutch: "bos", english: "forest", difficulty: "medium" },
  { dutch: "rust", english: "peace/calm", difficulty: "medium" },
  { dutch: "kring", english: "circle", difficulty: "medium" },
  { dutch: "grijs", english: "gray", difficulty: "medium" },
  { dutch: "haast", english: "rush", difficulty: "medium" },
  { dutch: "vlees", english: "meat", difficulty: "medium" },
  { dutch: "eis", english: "demand", difficulty: "medium" },
  { dutch: "streek", english: "region", difficulty: "medium" },
  { dutch: "smaak", english: "taste", difficulty: "medium" },
  { dutch: "traan", english: "tear", difficulty: "medium" },
  { dutch: "rij", english: "queue", difficulty: "medium" },
  { dutch: "spoor", english: "track", difficulty: "medium" },
  { dutch: "last", english: "burden", difficulty: "medium" },
  { dutch: "smal", english: "narrow", difficulty: "medium" },
  { dutch: "slot", english: "key lock", difficulty: "medium" },
  { dutch: "zwak", english: "weak", difficulty: "medium" },
  { dutch: "geur", english: "smell", difficulty: "medium" },
  { dutch: "buik", english: "stomach", difficulty: "medium" },
  { dutch: "flink", english: "hefty", difficulty: "medium" },
  { dutch: "beurt", english: "turn", difficulty: "medium" },
  { dutch: "wangen", english: "cheeks", difficulty: "medium" },
  { dutch: "vloer", english: "floor", difficulty: "medium" },
  { dutch: "rook", english: "smoke", difficulty: "medium" },
  { dutch: "slag", english: "battle", difficulty: "medium" },
  { dutch: "maan", english: "moon", difficulty: "medium" },
  { dutch: "wens", english: "wish", difficulty: "medium" },
  { dutch: "sfeer", english: "ambiance", difficulty: "medium" },
  { dutch: "bron", english: "source", difficulty: "medium" },
  { dutch: "rijk", english: "rich", difficulty: "medium" },
  { dutch: "droog", english: "dry", difficulty: "medium" },
  { dutch: "bord", english: "plate", difficulty: "medium" },
  { dutch: "jeugd", english: "youth", difficulty: "medium" },
  { dutch: "schoon", english: "clean", difficulty: "medium" },
  { dutch: "keel", english: "throat", difficulty: "medium" },
  { dutch: "pak", english: "business suit", difficulty: "medium" },
  { dutch: "broek", english: "pants", difficulty: "medium" },
  { dutch: "golf", english: "wave", difficulty: "medium" },
  { dutch: "lichaam", english: "body", difficulty: "medium" },
  { dutch: "groei", english: "growth", difficulty: "medium" },
  { dutch: "nat", english: "wet", difficulty: "medium" },
  { dutch: "duur", english: "expensive", difficulty: "medium" },
  { dutch: "feest", english: "party", difficulty: "medium" },
  { dutch: "reeks", english: "series", difficulty: "medium" },
  { dutch: "strak", english: "tight", difficulty: "medium" },
  { dutch: "kleed", english: "carpet", difficulty: "medium" },
  { dutch: "vlucht", english: "flight", difficulty: "medium" },
  { dutch: "dak", english: "roof", difficulty: "medium" },
  { dutch: "hals", english: "neck", difficulty: "medium" },
  { dutch: "geel", english: "yellow", difficulty: "medium" },
  { dutch: "streng", english: "strict", difficulty: "medium" },
  { dutch: "veld", english: "field", difficulty: "medium" },
  { dutch: "moe", english: "tired", difficulty: "medium" },
  { dutch: "geloof", english: "faith, belief", difficulty: "medium" },
  { dutch: "tak", english: "branch", difficulty: "medium" },
  { dutch: "tong", english: "tongue", difficulty: "medium" },
  { dutch: "kwijt", english: "lost", difficulty: "medium" },
  { dutch: "kaas", english: "cheese", difficulty: "medium" },
  { dutch: "zaal", english: "hall", difficulty: "medium" },
  { dutch: "greep", english: "grip", difficulty: "medium" },
  { dutch: "kust", english: "coast", difficulty: "medium" },
  { dutch: "boos", english: "angry", difficulty: "medium" },
  { dutch: "brug", english: "bridge", difficulty: "medium" },
  { dutch: "vak", english: "field, subject", difficulty: "medium" },
  { dutch: "strand", english: "beach", difficulty: "medium" },
  { dutch: "klant", english: "customer", difficulty: "medium" },
  { dutch: "fout", english: "mistake", difficulty: "medium" },
  { dutch: "moed", english: "courage", difficulty: "medium" },
  { dutch: "dom", english: "stupid", difficulty: "medium" },
  { dutch: "jas", english: "jacket", difficulty: "medium" },
  { dutch: "trots", english: "pride", difficulty: "medium" },
  { dutch: "zoet", english: "sweet", difficulty: "medium" },
  { dutch: "fiets", english: "bicycle", difficulty: "medium" },
  { dutch: "wolk", english: "cloud", difficulty: "medium" },
  { dutch: "kast", english: "closet", difficulty: "medium" },
  { dutch: "klap", english: "blow", difficulty: "medium" },
  { dutch: "stroom", english: "flow", difficulty: "medium" },
  { dutch: "winst", english: "profit", difficulty: "medium" },
  { dutch: "knap", english: "good looking", difficulty: "medium" },
  { dutch: "straf", english: "punishment", difficulty: "medium" },
  { dutch: "langzaam", english: "slow", difficulty: "medium" },
  { dutch: "boog", english: "bow", difficulty: "medium" },
  { dutch: "een poos", english: "a while", difficulty: "medium" },
  { dutch: "strekken", english: "stretch", difficulty: "medium" },
  { dutch: "brand", english: "fire", difficulty: "medium" },
  { dutch: "dwars", english: "transverse", difficulty: "medium" },
  { dutch: "kist", english: "chest", difficulty: "medium" },
  { dutch: "wand", english: "wall", difficulty: "medium" },
  { dutch: "klacht", english: "complaint", difficulty: "medium" },
  { dutch: "stuur", english: "steering wheel", difficulty: "medium" },
  { dutch: "kern", english: "core", difficulty: "medium" },
  { dutch: "leer", english: "leather", difficulty: "medium" },
  { dutch: "het liefst", english: "most preferably", difficulty: "medium" },
  { dutch: "dun", english: "thin", difficulty: "medium" },
  { dutch: "jurk", english: "dress", difficulty: "medium" },
  { dutch: "troep", english: "mess", difficulty: "medium" },
  { dutch: "hoed", english: "hat", difficulty: "medium" },
  { dutch: "sturen", english: "to send", difficulty: "medium" },
  { dutch: "tocht", english: "tour", difficulty: "medium" },
  { dutch: "mes", english: "knife", difficulty: "medium" },
  { dutch: "maat", english: "measure", difficulty: "medium" },
  { dutch: "poot", english: "leg", difficulty: "medium" },
  { dutch: "vent", english: "guy", difficulty: "medium" },
  { dutch: "maag", english: "stomach", difficulty: "medium" },
  { dutch: "lijk", english: "corpse", difficulty: "medium" },
  { dutch: "eer", english: "honor", difficulty: "medium" },
  { dutch: "mooi", english: "beautiful", difficulty: "medium" },
  { dutch: "kruis", english: "cross", difficulty: "medium" },
  { dutch: "doos", english: "box", difficulty: "medium" },
  { dutch: "vrucht", english: "fruit", difficulty: "medium" },
  { dutch: "klein", english: "small", difficulty: "medium" },
  { dutch: "makkelijk", english: "easy", difficulty: "medium" },
];
